name: asistencia_flutter
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  connectivity_plus: ^5.0.2
  flutter:
    sdk: flutter
  go_router: ^10.1.2 # (o la última versión)
  shared_preferences: ^2.5.2 # (o la última versión)
  http: ^0.13.6
  mobile_scanner: ^3.2.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  shared_preferences_web: ^2.4.3
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGO-192.png"
  adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/images/Icon-192.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/SOFTOWER_LOGIN.jpg
    - assets/images/SOFTOWER_LOGIN2.jpg
    - assets/images/FONDO_ASISTENCIA.webp
    - assets/images/HORA_DE_INGRESO.webp
    - assets/images/INICIO_ALMUERZO.webp
    - assets/images/FIN_ALMUERZO.webp
    - assets/images/HORA_DE_SALIDA.webp
    - assets/images/Icon-192.png
    - assets/images/LOGO-192.png
